version: '3.4'

services:
  eventmanagement:
    image: eventmanagement
    build:
      context: .
      dockerfile: EventManagement/EventManagements.Presentation/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}

  booking:
    image: booking
    build:
      context: .
      dockerfile: Booking/Bookings.Presentation/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
