global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'booking'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['booking:8080']
    tls_config:
      insecure_skip_verify: true
