name: CI/CD Pipeline for Event Booking Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          echo "$PRIVATE_KEY" > ssh-private-key && ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to your project directory or clone repo
            cd src/EventBooking || git clone https://github.com/lut2410/EB-Assignment src/EventBooking
            git pull

            # Start containers
            docker-compose down || true
            docker-compose up -d --build
          EOF
